name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spm_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  spm_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["6.0", "5.10"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  xcode_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: xcodebuild build -scheme GeoProjector-Package -destination 'platform=macOS'

  xcode_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: xcodebuild build -scheme GeoProjector-Package -destination 'name=iPhone 14' -sdk iphoneos

  cassini_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd Examples
          xcodebuild build -scheme 'Cassini' -destination 'platform=macOS'

  cassini_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd Examples
          xcodebuild build -scheme 'Cassini' -destination 'platform=iOS Simulator,name=iPhone 14' -sdk iphonesimulator
